// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneListApi;

namespace PhoneListApi.Migrations
{
    [DbContext(typeof(PhoneListContext))]
    partial class PhoneListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhoneListApi.DatabaseModel.PersonDetail", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("PersonId");

                    b.ToTable("PersonDetails");
                });

            modelBuilder.Entity("PhoneListApi.DatabaseModel.PhoneDetail", b =>
                {
                    b.Property<int>("PhoneDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PersonDetailPersonId");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("PhoneDetailId");

                    b.HasIndex("PersonDetailPersonId");

                    b.ToTable("PhoneDetails");
                });

            modelBuilder.Entity("PhoneListApi.DatabaseModel.PhoneDetail", b =>
                {
                    b.HasOne("PhoneListApi.DatabaseModel.PersonDetail", "PersonDetail")
                        .WithMany("PhoneDetails")
                        .HasForeignKey("PersonDetailPersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
